- id: 10.1126/science.adl5364
  type: paper
  description: Drug binding protein design.
  date: 2024-04
  image: 
  buttons:
    - type: manubot
      link: https://www.science.org/doi/10.1126/science.adl5364#F1
    - type: source
      text: Manuscript Source
      link: 
    - type: website
      link: http://manubot.org/
  tags:
    - open science
    - collaboration
  repo: 

- id: https://doi.org/10.1038/s41592-020-00985-5
  image: https://www.nature.com/articles/s41592-020-00985-5/figures/1
